# test flow that works
id: example_flow
namespace: final_project
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Hello, World, Haha!

triggers:
  - id: example_trigger
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/10 * * * *"  # Запускать каждую минуту
    backfill:
      start: "2023-10-01T00:00:00Z"  # Укажите дату в прошлом